framework:
    rate_limiter:
        anonymous_api:
            policy: 'sliding_window'
            limit: 100
            interval: '60 minutes'
        authenticated_api:
            policy: 'token_bucket'
            limit: 5000
            rate: { interval: '15 minutes', amount: 500 }

when@test:
    framework:
        rate_limiter:
            anonymous_api:
                policy: 'fixed_window'
                limit: 1000
