twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        locale: '%env(ETRAXIS_LOCALE)%'
        theme:  '%env(ETRAXIS_THEME)%'

when@test:
    twig:
        strict_variables: true
