language: php

php:
    - 8.1

env:
    global:
        - XDEBUG_MODE=coverage
    jobs:
        - DB=mysql
        - DB=postgresql

branches:
    only:
        - master

services:
    - mysql
    - postgresql

install:
    - cp config/travis/.env.$DB .env.local
    - cp config/travis/phpunit.$DB.xml phpunit.xml
    - composer --optimize-autoloader --no-interaction install

before_script:
    - ./bin/console --no-interaction doctrine:database:create
    - ./bin/console --no-interaction doctrine:migrations:migrate
    - ./bin/console --no-interaction doctrine:fixtures:load
    - ./bin/console --no-interaction etraxis:fake-webpack

script:
    - ./bin/phpunit --coverage-clover=coverage.clover
    - composer global require scrutinizer/ocular:^1.9
    - php ~/.config/composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
